Template.searchBox.onRendered(function () {
    Meteor.setTimeout(function () {
      $("#searchBox").autocomplete({
        minLength: 3
      }, {
        source: function (request, response) {
          console.log("search term " + request.term);
          return Meteor.call("searchProducts", request.term, function (error, result) {
            if (error) {
              console.log(error);
            }
            if (result) {
              return response(result);
            }
          });
        }
      })
      //  .data("ui-autocomplete")._renderItem = function (ul, item) {
      //  var listItemHtml;
      //  listItemHtml = "<a href=\"/product/" + item.id + "\"> " + item.value + "\n  <span class=\"search-item-price\">\n    $" + item.price + "\n  </span>\n</a>";
      //  //listItemHtml = '<a href="'+ReactionRouter.pathFor('/product/', item.id)+'"> ' + item.value + '\n	<span class="search-item-price">\n		$' + item.price + '\n	</span>\n</a>';
      //  return $("<li>").html(listItemHtml).appendTo(ul);
      //};

    }, 1000);

    $('#searchBoxDate').datepicker();

    $("#searchBoxDate").autocomplete({
      minLength: 8
    });

  }
);
Template.searchBox.events({
  'focus #searchBoxDate': function (event) {
    var date = $('#searchBoxDate').val().split('/');
    console.log(date);
    var dateNew = date[2] + "-" + date[0] + '-' + date[1];
    console.log(dateNew);
    Meteor.call("searchProductsByDate", dateNew, function (error, result) {
      if (error) {
        console.log(error);
      }
      if (result) {
        console.log(result);
        Session.set('ProductList', result);
      }
    });
  }
  // Anything else on #date-id focus?

})

// ---
// generated by coffee-script 1.9.2
