
Template.searchBox.onRendered(
	function() {

	  $('#searchBoxDate').datepicker();

		GoogleMaps.load();

		Meteor.setTimeout(function() {
			/*
		  $("#searchBox").autocomplete({
		    minLength: 3
		  }, {
		    source: function(request, response) {
		      console.log("search term " + request.term);
		      return Meteor.call("searchProducts", request.term, function(error, result) {
		        if (error) {
		          console.log(error);
		        }
		        if (result) {
		          return response(result);
		        }
		      });
		    }
		  }).data("ui-autocomplete")._renderItem = function(ul, item) {
		    var listItemHtml;
		    listItemHtml = "<a href=\"/product/" + item.id + "\"> " + item.value + "\n  <span class=\"search-item-price\">\n    $" + item.price + "\n  </span>\n</a>";
				//listItemHtml = '<a href="'+ReactionRouter.pathFor('/product/', item.id)+'"> ' + item.value + '\n	<span class="search-item-price">\n		$' + item.price + '\n	</span>\n</a>';
		    return $("<li>").html(listItemHtml).appendTo(ul);
		  }; */

			/*
		  return $("#searchBoxDate").autocomplete({
		    minLength: 8,
		    source: function(request, response) {
					let filterDate = new Date(request.term);
		      console.log("search date new: ",filterDate," old: ",Session.get('productFilters/forSaleOnDate'));
					Session.set('productFilters/forSaleOnDate', filterDate);
		      return Meteor.call("searchProductsByDate", request.term, function(error, result) {
		        if (error) {
		          console.log(error);
		        }
		        if (result) {
		          return response(result);
		        }
		      });
		    }
		  }).data("ui-autocomplete")._renderItem = function(ul, item) {
		    var listItemHtml;
//		    listItemHtml = '<a href="/product/' + item.id + '"> ' + item.value + '\n	<span class="search-item-price">\n		$' + item.price + '\n	</span>\n</a>';
				listItemHtml = '<a href="'+ReactionRouter.pathFor('product', item.id)+'"> ' + item.value + '\n	<span class="search-item-price">\n		$' + item.price + '\n	</span>\n</a>';
		    return $("<li>").html(listItemHtml).appendTo(ul);
		  };
			/*/

		}, 1000);
	}
);

Template.searchBox.events(
	{
			"change #searchBoxDate": function(event) {
				const value = event.target.value;
				let filterDate = new Date(value);
				console.log("search date new: ",filterDate," old: ",Session.get('productFilters/forSaleOnDate'));
				Session.set('productFilters/forSaleOnDate', filterDate);
			},
			"change #searchBoxLocation": function(event) {
				const value = event.target.value;
				let addressString = value+", Switzerland";

				if (GoogleMaps.loaded()) {
					var geocoder = new google.maps.Geocoder();

	        geocoder.geocode(
	          {
	            'address': addressString
	          },
	          function(results, status) {
	             if(status == google.maps.GeocoderStatus.OK) {
	                let location = results[0].geometry.location;
	                console.log("resolved search : "+location.lat()+"/"+location.lng());

									let filterLocation = location.lat()+"/"+location.lng();
									console.log("search location new: ",filterLocation," old: ",Session.get('productFilters/location'));
									Session.set('productFilters/location', filterLocation);
	              }
	          }
	        );
		    }
			},

	}
);

// ---
// generated by coffee-script 1.9.2
